# -*- coding: utf-8 -*-
"""burnaway-data-science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qRwt1MYyPM3t_dNfj7iYSwg4MNgNNfQ

# **Capstone Project (Data Science): BurnAway**

## **Informasi Dataset**

### **Sumber Dataset**

**Kaggle:** https://www.kaggle.com/datasets/asifxzaman/developer-burnout-prediction-dataset7000-samples

### **Fitur Utama**

- **`age`**: Usia developer dalam satuan tahun.
- **`experience_years`**: Total durasi pengalaman kerja profesional dalam hitungan tahun.
- **`daily_work_hours`**: Durasi waktu yang digunakan untuk bekerja setiap hari.
- **`sleep_hours`**: Durasi waktu istirahat tidur dalam satu hari.
- **`caffeine_intake`**: Jumlah konsumsi kafein harian dalam hitungan cangkir.
- **`bugs_per_day`**: Jumlah kesalahan pada kode yang dihasilkan setiap hari.
- **`commits_per_day`**: Jumlah riwayat pengiriman kode ke repositori dalam sehari.
- **`meetings_per_day`**: Jumlah pertemuan yang harus dihadiri developer setiap hari.
- **`screen_time`**: Total durasi waktu menatap layar perangkat digital harian.
- **`exercise_hours`**: Durasi waktu untuk melakukan aktivitas fisik harian.
- **`stress_level`**: Skor tingkat stres dalam rentang 0 sampai 100.
- **`burnout_level`**: Variabel target yang menunjukkan tingkat burnout developer.

## **Latar Belakang Masalah**

Masalah

## **Menentukan Pertanyaan Bisnis**

- Pertanyaan 1: Bagaimana pengaruh faktor jam kerja, waktu tidur, dan intensitas penggunaan layar terhadap tingkat burnout pada developer?
- Pertanyaan 2: Bagaimana pengaruh keseimbangan antara jam kerja dan waktu tidur terhadap tingkat burnout pada developer?
- Pertanyaan 3: Bagaimana pengaruh tingkat stres terhadap tingkat burnout pada developer?
- Pertanyaan 4: Apakah intensitas paparan layar yang tinggi relatif terhadap jam kerja secara signifikan meningkatkan resiko burnout yang lebih berat?
- Pertanyaan 5: Bagaimana hubungan antara efisiensi kerja dengan tingkat burnout developer? Apakah developer dengan efisiensi rendah cenderung mengalami burnout lebih tinggi?

## **Import Library**
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from google.colab import files
from sklearn.preprocessing import LabelEncoder

"""## **Data Wrangling**

### **Gathering Data**
"""

# Upload dataset
uploaded = files.upload()
print("\n")

df = pd.read_csv("developer_burnout_dataset_7000.csv")
df

"""**Insight:**
- Dataset developer burnout berhasil ditampilkan dalam 5 baris pertama dan 5 baris terakhir.
- Dataset ini masih memiliki value NaN dibeberapa kolom dan perlu ditangani pada tahap cleaning berikutnya.
- Dataset ini memiliki 7.000 baris dan 12 kolom.

### **Assessing Data**
"""

df.info()

"""**Insight:**
- Dataset ini memiliki 7.000 baris, namun pada bagian Non-Null Count, terlihat semua kolom hanya memiliki 6.860 baris data yang terisi. Hal ini menandakan adanya data yang hilang dan perlu ditangani pada tahap cleaning berikutnya.
- Hampir semua kolom bertipe float64, kecuali kolom burnout_level yang bertipe object (string).
"""

df.isna().sum()

"""**Insight:**
- Terlihat kalau setiap kolom memiliki 140 nilai yang kosong. Nilai yang kosong ini akan diisi menggunakan metode imputasi pada tahap cleaning berikutnya.
"""

df.duplicated().sum()

"""**Insight:**
- Tidak ditemukan adanya data yang terduplikasi pada dataset ini.
"""

df.describe()

"""**Insight:**
- Rata-rata developer dalam dataset ini berusia sekitar 32 tahun, dengan rentang usia paling muda 20 tahun dan paling tua 44 tahun.
- Rata-rata developer bekerja selama 9 jam/hari, namun rata-rata waktu tidurnya hanya 6,4 jam/hari.
- Rata-rata developer mengkonsumsi kafein 3,5 unit/hari, dengan maksimal mencapai 7 unit/hari.
- Rata-rata developer memiliki level stres yang mencapai 53,6 dengan skala 0 hingga 100.

### **Cleaning Data**
"""

# Membuat salinan dataframe
df_clean = df.copy()

# Imputasi kolom numerik dengan nilai median
numerical_cols = df_clean.select_dtypes(include=['float64']).columns
medians = df_clean[numerical_cols].median()
print("=== Nilai Median Untuk Imputasi Kolom Numerik ===")
print(medians)
print("\n")
df_clean[numerical_cols] = df_clean[numerical_cols].fillna(medians)

# Imputasi kolom kategorikal dengan Nilai Modus
categorical_col = df_clean['burnout_level'].mode()[0]
df_clean['burnout_level'] = df_clean['burnout_level'].fillna(categorical_col)
print(f"Nilai Modus Untuk Imputasi Kolom burnout_level: {categorical_col}")

# Verifikasi
print("\n=== Cek DataFrame Setelah Imputasi ===")
df_clean.info()

"""**Insight:**
- Setiap kolom numerik berhasil diisi dengan nilai tengah (median).
- Kolom burnout_level diisi dengan nilai Medium (modus). Hal ini menunjukkan bahwa secara mayoritas, developer dalam dataset ini berada pada tingkat burnout menengah.
- Dataset kini memiliki 7.000 baris pada bagian Non-Null Count. Hal ini menunjukkan bahwa tidak ada lagi data yang hilang pada setiap kolom.

## **Feature Engineering**
"""

# Fitur rasio beban kerja dan istirahat
df_clean['work_sleep_ratio'] = df_clean['daily_work_hours'] / (df_clean['sleep_hours'] + 0.1)

# Fitur intensitas paparan layar
df_clean['screen_time_intensity'] = df_clean['screen_time'] / (df_clean['daily_work_hours'] + 0.1)

# Fitur efisiensi produksi
df_clean['commit_bug_ratio'] = df_clean['commits_per_day'] / (df_clean['bugs_per_day'] + 0.1)

# Fitur kategori keseimbangan beban kerja dan istirahat
df_clean['work_category'] = pd.cut(
    df_clean['work_sleep_ratio'],
    bins=[0, 1, 2, 3, 10],
    labels=['Seimbang', 'Cukup Tinggi', 'Tinggi', 'Sangat Tinggi']
)

# Verifikasi
print("=== Cek DataFrame Setelah Feature Engineering ===")
df_clean.info()

# Menampilkan 5 baris pertama fitur baru
print("\n=== Sampel Fitur Baru Terhadap Level Burnout ===")
df_clean[['work_sleep_ratio', 'screen_time_intensity', 'commit_bug_ratio', 'work_category', 'burnout_level']].head()

"""**Insight:**
- Fitur baru work_sleep_ratio berhasil dibuat. Fitur ini mengukur keseimbangan antara waktu kerja dan waktu tidur untuk mendeteksi potensi kelelahan fisik secara kuantitatif.
- Fitur baru screen_time_intensity berhasil dibuat. Fitur ini memantau durasi penggunaan perangkat digital selama jam kerja untuk melihat beban mata dan mental bagi developer.
- Fitur baru commit_bug_ratio berhasil dibuat. Fitur ini menilai perbandingan hasil kerja terhadap kesalahan yang muncul sebagai indikator performa kerja harian.
- Fitur baru work_category berhasil dibuat. Fitur ini mengelompokkan rasio kerja dan tidur ke dalam kategori kualitatif untuk mempermudah interpretasi tingkat resiko beban kerja dan istirahat.
- 4 Fitur baru tersebut berhasil ditampilkan dalam 5 baris pertama.

## **Label Encoding**
"""

# Mapping kolom level burnout
df_clean['burnout_level'] = df_clean['burnout_level'].map({
    'Low': 0,
    'Medium': 1,
    'High': 2
})

# Mapping kolom kategori keseimbangan beban kerja dan istirahat
df_clean['work_category'] = df_clean['work_category'].map({
    'Seimbang': 0,
    'Cukup Tinggi': 1,
    'Tinggi': 2,
    'Sangat Tinggi': 3
}).astype(int)

df_clean.head()

"""**Insight:**
- Kolom burnout_level dan work_category berhasil dikonversi menjadi bentuk numerik.
- Pada kolom burnout_level, nilai 0 merepresentasikan tingkat burnout rendah (Low), nilai 1 merepresentasikan tingkat burnout sedang (Medium), dan nilai 2 merepresentasikan tingkat burnout tinggi (High).
- Pada kolom work_category, nilai 0 merepresentasikan kategori Seimbang, nilai 1 merepresentasikan kategori Cukup Tinggi, nilai 2 merepresentasikan kategori Tinggi, dan nilai 3 merepresentasikan kategori Sangat Tinggi.
- Proses encoding dilakukan secara manual untuk menjaga urutan ordinal dari tingkat burnout.

## **Exploratory Data Analysis (EDA)**
"""

# EDA untuk pertanyaan 1
print("=== Faktor Fisik Terhadap Tingkat Burnout ===")
display(df_clean.groupby(by="burnout_level").agg({
    "daily_work_hours": ["mean", "max", "min"],
    "sleep_hours": ["mean", "max", "min"],
    "screen_time": ["mean", "max", "min"]
}))

# EDA untuk pertanyaan 2
print("\n\n=== Rasio Beban Kerja dan Istirahat Terhadap Tingkat Burnout ===")
display(df_clean.groupby(by="work_category", observed=False).agg({
    "burnout_level": ["mean", "max", "min"]
}))

# EDA untuk pertanyaan 3
print("\n\n=== Tingkat Stres Terhadap Tingkat Burnout ===")
display(df_clean.groupby(by="burnout_level").agg({
    "stress_level": ["mean", "max", "min"]
}))

# EDA untuk pertanyaan 4
print("\n\n=== Intensitas Paparan Layar Terhadap Tingkat Burnout ===")
display(df_clean.groupby(by="burnout_level").agg({
    "screen_time_intensity": ["mean", "median", "std"]
}))

# EDA untuk pertanyaan 5
print("\n\n=== Efisiensi Produksi Dengan Tingkat Burnout ===")
display(df_clean.groupby(by="burnout_level").agg({
    "commit_bug_ratio": ["mean", "median", "std"]
}))

"""**Insight:**
- Developer pada burnout level 2 (High) memiliki rata-rata jam kerja (11,12 jam) dan screen time (14,07 jam) tertinggi, serta durasi tidur paling rendah (6,09 jam) dibandingkan level lainnya.
- Burnout level 1 (Medium) secara konsisten berada di titik tengah untuk semua parameter, menunjukkan adanya korelasi linear antara beban kerja dengan tingkat burnout.
- Peningkatan rasio antara beban kerja dan waktu istirahat berbanding lurus dengan kenaikan rata-rata tingkat burnout pada setiap kategori.
- Rasio beban kerja dan istirahat pada kategori 3 (Sangat Tinggi) mencatatkan rata-rata burnout tertinggi sebesar 1,74 sementara kategori 0 (Seimbang) memiliki angka terendah di level 0,5.
- Rata-rata level stres meningkat drastis dari angka 22,76 pada burnout level 0 (Low) hingga mencapai puncaknya di angka 82,74 pada burnout level 2 (High).
- Rata-rata intensitas paparan layar menurun secara bertahap seiring kenaikan tingkat burnout, dengan angka terendah sebesar 1,26 pada level 2 (High) yang menunjukkan jam kerja yang semakin panjang mulai mendominasi total durasi penggunaan perangkat secara keseluruhan.
- Efisiensi kerja mengalami penurunan drastis dari rata-rata 18,46 pada burnout level 0 (Low) menjadi hanya 2,9 pada burnout level 2 (High), membuktikan bahwa tingkat burnout yang tinggi berdampak buruk pada kualitas dan produktivitas hasil kerja developer.

## **Visualization & Explanatory Analysis**

### **Pertanyaan Bisnis 1: Bagaimana pengaruh faktor jam kerja, waktu tidur, dan intensitas penggunaan layar terhadap tingkat burnout pada developer?**
"""

# Agregasi data untuk Menghitung rata-rata faktor per level burnout
eda_plot = df_clean.groupby("burnout_level")[[
    "daily_work_hours",
    "sleep_hours",
    "screen_time"
]].mean().reset_index()

# Transformasi data ke format long
eda_melted = eda_plot.melt(
    id_vars="burnout_level",
    var_name="Faktor",
    value_name="Rata-rata"
)

# Skema warna
palette_base = sns.color_palette("Blues", 6)
colors = {0: palette_base[1], 1: palette_base[3], 2: palette_base[5]}

plt.figure(figsize=(12, 7))
ax = sns.barplot(
    data=eda_melted,
    x="Faktor",
    y="Rata-rata",
    hue="burnout_level",
    palette=colors,
    errorbar=None
)
max_val = eda_melted["Rata-rata"].max()
plt.ylim(0, max_val * 1.2)
plt.title("Perbandingan Pengaruh Faktor Fisik Terhadap Tingkat Burnout", fontsize=14, fontweight='bold', pad=20)
plt.ylabel("Rata-Rata Jam", fontsize=12)
plt.xlabel("Faktor Fisik", fontsize=12)
plt.xticks(ticks=[0, 1, 2], labels=["Daily Work Hours", "Sleep Hours", "Screen Time"], fontsize=11)

# Legend custom
low_patch = mpatches.Patch(color=colors[0], label='0 (Low)')
med_patch = mpatches.Patch(color=colors[1], label='1 (Medium)')
high_patch = mpatches.Patch(color=colors[2], label='2 (High)')
plt.legend(handles=[low_patch, med_patch, high_patch], title="Level Burnout", loc='upper left')

# Label angka di atas setiap bar
for p in ax.patches:
    if p.get_height() > 0:
        ax.annotate(format(p.get_height(), '.2f'),
                    (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha = 'center', va = 'center',
                    xytext = (0, 12),
                    textcoords = 'offset points',
                    fontweight='bold')

plt.tight_layout()
plt.show()

"""**Insight:**
- Developer dengan burnout High memiliki rata-rata jam kerja (11,13 jam) dan waktu layar (14,08 jam) paling tinggi, serta waktu tidur (6,09 jam) paling rendah.
- Developer dengan burnout Low menunjukkan kondisi sebaliknya yaitu jam kerja lebih rendah (6,74 jam), waktu layar lebih kecil (9,75 jam), dan waktu tidur lebih cukup (6,97 jam).
- Developer dengan burnout Medium berada di antara keduanya, menunjukkan pola yang konsisten.
- Pola ini mengindikasikan bahwa peningkatan jam kerja dan waktu layar, serta penurunan waktu tidur, berkontribusi signifikan terhadap kenaikan tingkat burnout.

### **Pertanyaan Bisnis 2: Bagaimana pengaruh keseimbangan antara jam kerja dan waktu tidur terhadap tingkat burnout pada developer?**
"""

# Agregasi data untuk mencari nilai tertinggi
avg_work_burnout = df_clean.groupby('work_category', observed=False)['burnout_level'].mean()
max_val = avg_work_burnout.max()

# Skema warna
palette_base = sns.color_palette("Greens", 6)
base_color = palette_base[1]
highlight_color = palette_base[4]

# List warna berdasarkan kondisi
colors = [highlight_color if i == avg_work_burnout.idxmax() else base_color for i in avg_work_burnout.index]

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x=avg_work_burnout.index,
    y=avg_work_burnout.values,
    palette=colors,
    hue=avg_work_burnout.index,
    legend=False,
    errorbar=None
)
ax.set_xticks(range(len(avg_work_burnout.index)))
ax.set_xticklabels(['Seimbang', 'Cukup Tinggi', 'Tinggi', 'Sangat Tinggi'], fontsize=11)
plt.ylim(0, max_val * 1.2)
plt.title('Pengaruh Rasio Beban Kerja dan Istirahat Terhadap Tingkat Burnout', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Kategori Beban Kerja dan Istirahat', fontsize=12)
plt.ylabel('Rata-Rata Level Burnout', fontsize=12)

# Label angka di atas bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 12),
                textcoords = 'offset points',
                fontweight='bold')

plt.tight_layout()
plt.show()

"""**Insight:**
- Terdapat kenaikan yang konsisten pada rata-rata burnout seiring meningkatnya kategori beban kerja dan istirahat (dari 0,51 ke 1,74).
- Kategori Sangat Tinggi memiliki burnout tertinggi, menunjukkan kondisi kerja jauh lebih dominan dibanding waktu istirahat.
- Kategori Seimbang memiliki burnout paling rendah, menandakan keseimbangan kerja dan tidur mampu menekan resiko burnout.
- Perbedaan antar kategori terlihat cukup signifikan, sehingga rasio kerja terhadap istirahat menjadi indikator kuat dalam memprediksi tingkat burnout developer.

### **Pertanyaan Bisnis 3: Bagaimana pengaruh tingkat stres terhadap tingkat burnout pada developer?**
"""

# Agregasi data untuk mencari nilai tertinggi
avg_stress = df_clean.groupby('burnout_level', observed=False)['stress_level'].mean()
max_val = avg_stress.max()

# Skema warna
palette_base = sns.color_palette("Reds", 6)
base_color = palette_base[1]
highlight_color = palette_base[4]

# List warna berdasarkan kondisi
colors = [highlight_color if i == avg_stress.idxmax() else base_color for i in avg_stress.index]

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x=avg_stress.index,
    y=avg_stress.values,
    palette=colors,
    hue=avg_stress.index,
    legend=False,
    errorbar=None
)
ax.set_xticks(range(len(avg_stress.index)))
ax.set_xticklabels(['Low', 'Medium', 'High'], fontsize=11)
plt.ylim(0, max_val * 1.2)
plt.title('Pengaruh Tingkat Stres Terhadap Tingkat Burnout', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Level Burnout', fontsize=12)
plt.ylabel('Rata-Rata Level Stres', fontsize=12)

# Label angka di atas bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 12),
                textcoords = 'offset points',
                fontweight='bold')

plt.tight_layout()
plt.show()

"""**Insight:**
- Rata-rata tingkat stres meningkat tajam dari Low (22,77) ke Medium (52,93) lalu ke High (82,75).
- Developer dengan burnout High memiliki tingkat stres yang jauh lebih tinggi dibanding kategori lainnya.
- Kenaikan ini menunjukkan pola yang sangat konsisten dan signifikan antar tingkat burnout.
- Hal ini mengindikasikan bahwa  tingkat stres merupakan faktor yang sangat kuat dan dominan dalam memengaruhi tingkat burnout developer.

### **Pertanyaan Bisnis 4: Apakah intensitas paparan layar yang tinggi relatif terhadap jam kerja secara signifikan meningkatkan resiko burnout yang lebih berat?**
"""

# Agregasi data untuk mencari nilai tertinggi
avg_intensity = df_clean.groupby('burnout_level', observed=False)['screen_time_intensity'].mean()
max_val = avg_intensity.max()

# Skema warna
palette_base = sns.color_palette("Purples", 6)
base_color = palette_base[1]
highlight_color = palette_base[4]

# List warna berdasarkan kondisi
colors = [highlight_color if i == avg_intensity.idxmax() else base_color for i in avg_intensity.index]

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x=avg_intensity.index,
    y=avg_intensity.values,
    palette=colors,
    hue=avg_intensity.index,
    legend=False,
    errorbar=None
)
ax.set_xticks(range(len(avg_intensity.index)))
ax.set_xticklabels(['Low', 'Medium', 'High'], fontsize=11)
plt.ylim(0, max_val * 1.2)
plt.title('Pengaruh Intensitas Paparan Layar Terhadap Tingkat Burnout', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Level Burnout', fontsize=12)
plt.ylabel('Rata-Rata Intensitas Waktu Layar', fontsize=12)

# Label angka di atas bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 12),
                textcoords = 'offset points',
                fontweight='bold')

plt.tight_layout()
plt.show()

"""**Insight:**
- Developer dengan burnout Low memiliki rata-rata intensitas waktu layar paling tinggi (1,46) dibandingkan kategori lainnya.
- Developer dengan burnout High menunjukkan rata-rata intensitas paling rendah (1,27).
- Penurunan angka intensitas pada tingkat burnout High menandakan bahwa kenaikan total jam kerja harian meningkat jauh lebih pesat daripada durasi penggunaan layar.
- Hasil ini mengindikasikan bahwa beban jam kerja secara keseluruhan merupakan faktor pendorong burnout yang lebih kuat dibandingkan rasio penggunaan layar terhadap jam kerja.

### **Pertanyaan Bisnis 5: Bagaimana hubungan antara efisiensi kerja dengan tingkat burnout developer? Apakah developer dengan efisiensi rendah cenderung mengalami burnout lebih tinggi?**
"""

# Agregasi data untuk mencari nilai tertinggi
avg_efficiency = df_clean.groupby('burnout_level')['commit_bug_ratio'].mean()
max_val = avg_efficiency.max()

# Skema warna
palette_base = sns.color_palette("Blues", 6)
base_color = palette_base[1]
highlight_color = palette_base[4]

# List warna berdasarkan kondisi
colors = [highlight_color if i == avg_efficiency.idxmax() else base_color for i in avg_efficiency.index]

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x=avg_efficiency.index,
    y=avg_efficiency.values,
    palette=colors,
    hue=avg_efficiency.index,
    legend=False,
    errorbar=None
)
ax.set_xticks(range(len(avg_efficiency.index)))
ax.set_xticklabels(['Low', 'Medium', 'High'], fontsize=11)
plt.ylim(0, max_val * 1.2)
plt.title('Hubungan Antara Efisiensi Produksi Dengan Tingkat Burnout', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Level Burnout', fontsize=12)
plt.ylabel('Rata-Rata Rasio Commit dan Bug', fontsize=12)

# Label angka di atas bar
for p in ax.patches:
    ax.annotate(format(p.get_height(), '.2f'),
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 12),
                textcoords = 'offset points',
                fontweight='bold')

plt.tight_layout()
plt.show()

"""**Insight:**
- Developer dengan tingkat burnout Low memiliki rata-rata rasio commit terhadap bug paling tinggi yaitu sebesar 18,47.
- Developer dengan tingkat burnout High mencatatkan skor efisiensi paling rendah yaitu hanya sebesar 2,91.
- Terjadi penurunan efisiensi kerja yang sangat signifikan dan konsisten seiring dengan meningkatnya level burnout dari Low ke High.
- Data ini menunjukkan bahwa rendahnya efisiensi kerja yang diukur melalui rasio commit dan bug berkorelasi kuat dengan tingginya tingkat burnout pada developer.

## **Conclusion Analysis**

- **Conclusion Pertanyaan 1:**
- **Conclusion Pertanyaan 2:**
- **Conclusion Pertanyaan 3:**
- **Conclusion Pertanyaan 4:**
- **Conclusion Pertanyaan 5:**

## **A/B Testing**
"""

# from scipy.stats import ttest_ind

# # Kelompok A = burnout rendah
# group_A = df_clean[df_clean['burnout_level'] == 'Low']['daily_work_hours']

# # Kelompok B = burnout tinggi
# group_B = df_clean[df_clean['burnout_level'] == 'High']['daily_work_hours']

# # Uji t-test
# t_stat, p_value = ttest_ind(group_A, group_B)

# print("T-statistic:", t_stat)
# print("P-value:", p_value)

"""**Insight:**
- Hasil uji statistik menunjukkan nilai p-value < 0.05, sehingga terdapat perbedaan yang signifikan antara jam kerja pada developer dengan burnout rendah dan tinggi.
- Developer dengan burnout tinggi memiliki jam kerja yang secara signifikan lebih tinggi dibandingkan dengan burnout rendah.
- Hal ini menunjukkan bahwa jam kerja merupakan faktor yang berpengaruh signifikan terhadap tingkat burnout.

## **Export Dataset**
"""

df_clean.to_csv("burnout_main_data.csv", index=False)

"""**Insight:**
- Dataset yang sudah clean berhasil diekspor ke dalam file CSV.
"""